### ISSUE TITLE
Too many KMS master keys created

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#239]
We're creating far too many KMS master keys. There are now ~20 more KMS keys in eu-central-1 in about 12 hours even though we've only launched 2 or 3 clusters.

I think its a problem with changing to a ListWatch and the KMS key creation logic. This logging looks suspicious. I think we need to check for a key with the alias before creating the key.

```
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:180","info":"creating cluster 'zv2m4'","time":"17-05-17 06:57:36.019"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:217","info":"keypair 'zv2m4' already exists, reusing","time":"17-05-17 06:57:36.510"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:220","info":"waiting for k8s secrets...","time":"17-05-17 06:57:36.510"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:227","info":"created KMS key for cluster 'zv2m4'","time":"17-05-17 06:57:36.552"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:237","error":"could not create KMS key: [{/go/src/github.com/giantswarm/aws-operator/resources/aws/kms.go:36: } {AlreadyExistsException: An alias with the name arn:aws:kms:eu-west-1:292127003750:alias/zv2m4 already exists\n\tstatus code: 400, request id: 1c1631a0-3ace-11e7-bfb2-a1e7ce797414}]","time":"17-05-17 06:57:36.708"}
```

**Comment by asymmetric** [comment]
It turns out it's [not possible](https://docs.aws.amazon.com/cli/latest/reference/kms/list-aliases.html) to query for an alias using the AWS API. You can only get *all* aliases, paginated.

But anyway, I don't think this is our issue, because when we create a cluster:

* we create a key
* we try to create an alias, it fails
* the operator stops

Then when we delete:

* we schedule the deletion of the key
* we delete the alias

So I don't see why we would be left with tons of keys without aliases.

**Comment by rossf7** [comment]
Its really annoying that the KMS API doesn't support this. This is still happening in FRA and should be easier to debug as there are less keys.
