### ISSUE TITLE
cloudconfig: abstract away differences between AWS and KVM etcd/calico services

### ISSUE THREAD

**Issue by iaguis** [giantswarm/aws-operator#72]
We need to do more things in the KVM operator:

* Write master IP on the outer etcd
* Add flannel bridge in calico
* Write to `/calico/v1/host/{{.Node.Hostname}}-flannel/bird_ip` in cluster etcd

We need to abstract those differences away

**Comment by nhlfr** [comment]
I don't think it will be needed. Since we're going to move to self-hosted Calico, and running it is just a `kubectl` one-liner, we can create oneshot services for Calico in operators, not in the main k8scloudconfig repo. I think it's better to define networking in each operator and don't care about that we copy&paste only one line, than to introduce more abstraction into cloudconfig generation.

Ref https://github.com/giantswarm/k8scloudconfig/issues/40

Feel free to re-open if you don't agree.
